services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-net

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "mayes0art@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ../pgadmin/servers.json:/pgadmin4/servers.json
      - ../data/pgadmin:/var/lib/pgadmin
    networks:
      - app-net


  api:
    build:
      context: .
    container_name: py-web-api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - ./app:/code/app
    ports:
      - 80:80
    networks:
      - app-net

networks:
  app-net:
    driver: bridge